from flask_login import UserMixin
from datetime import datetime

from app import db

class RentalHouse(db.Model):
    HouseID = db.Column(db.Integer, primary_key=True, nullable=False)
    HouseName = db.Column(db.Text, nullable=False)
    neighbourhood_cleansed = db.Column(db.Text, nullable=False)
    neighbourhood_group_cleansed = db.Column(db.Text, nullable=False)
    picture_url = db.Column(db.Text, nullable=False)
    latitude = db.Column(db.Float, nullable=False)
    longitude = db.Column(db.Float, nullable=False)
    room_type = db.Column(db.Text, nullable=False)
    price = db.Column(db.Integer, nullable=False)
    minimum_months = db.Column(db.Integer, nullable=False)
    maximum_months = db.Column(db.Integer, nullable=False)
    distance_to_mrt = db.Column(db.Float, nullable=False)
    closest_mrt_name = db.Column(db.Text, nullable=False)
    closest_mrt_stop_id = db.Column(db.Text, nullable=False)
    closest_mall_distance = db.Column(db.Float, nullable=False)
    closest_mall_name = db.Column(db.Text, nullable=False)
    closest_mall_address = db.Column(db.Text, nullable=False)
    conditioning = db.Column(db.Boolean, nullable=False)
    BBQ = db.Column(db.Boolean, nullable=False)
    gym = db.Column(db.Boolean, nullable=False)
    pool = db.Column(db.Boolean, nullable=False)
    dryer = db.Column(db.Boolean, nullable=False)
    Wifi = db.Column(db.Boolean, nullable=False)
    kitchen = db.Column(db.Boolean, nullable=False)
    Backyard = db.Column(db.Boolean, nullable=False)
    TV = db.Column(db.Boolean, nullable=False)
    refrigerator = db.Column(db.Boolean, nullable=False)
    Microwave = db.Column(db.Boolean, nullable=False)
    Oven = db.Column(db.Boolean, nullable=False)
    Pets = db.Column(db.Boolean, nullable=False)
    stove = db.Column(db.Boolean, nullable=False)
    fan = db.Column(db.Boolean, nullable=False)